<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="test_one" errors="1" failures="0" skipped="0" tests="1" time="4.751" timestamp="2024-12-03T11:50:27.645476+05:30" hostname="ALZAHEDI-DEV"><testcase time="0.000" /><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\logging.py", line 803, in pytest_runtestloop
    return (yield)  # Run all the tests.
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\terminal.py", line 673, in pytest_runtestloop
    result = yield
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\warnings.py", line 112, in pytest_runtest_protocol
    return (yield)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\assertion\__init__.py", line 176, in pytest_runtest_protocol
    return (yield)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\unittest.py", line 429, in pytest_runtest_protocol
    res = yield
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\faulthandler.py", line 88, in pytest_runtest_protocol
    return (yield)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\runner.py", line 244, in call_and_report
    report: TestReport = ihook.pytest_runtest_makereport(item=item, call=call)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\tmpdir.py", line 310, in pytest_runtest_makereport
    rep = yield
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\_pytest\skipping.py", line 269, in pytest_runtest_makereport
    rep = yield
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\venv\lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "E:\Alfurquan\Self-Learning\Python\subprocess-vs-psutils\test\conftest.py", line 12, in pytest_runtest_makereport
    report.longreprtext = custom_message  # Override the long failure message
AttributeError: can't set attribute 'longreprtext'</error></testcase></testsuite></testsuites>